### ISSUE TITLE
`fetch()` should (optionally) store downloads in a cache directory.

### ISSUE THREAD

**Issue by bruxisma** [slurps-mad-rips/ixm#16]
# Feature Request

`fetch()` should (optionally) store downloads in a cache directory

***

## What is the current behavior?

`fetch()` will currently do what the `FetchContent` API does, which is place all source and build dependencies in the build directory. 

***

## Why should this be changed or added?

FetchContent supports manually setting the source and binary directories. To reduce disk footprint (as well as support caching dependencies in CI), we should follow the general XDG naming guidelines for the given cache.

***

## How would you implement this?

This might take a bit of work, but in the end we'll have an XDG-like function and properties for customization. The important part is getting the CACHE directory set for use. It's currently up for debate if the XDG functions should be made available to everyone.

**Comment by slurps-mad-rips** [comment]
Currently, there is some logic regarding the idea of appdirs (XDG/LOCALAPPDATA/etc.). IXM sets these as properties at present (with fallback logic to allow users to override via the `XDG_*` environment variables, or by overriding soon-to-be-documented properties). However we're not currently using them. Once we do start using them we can start placing certain downloads into the cache directory, and eventually close this.

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
